# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rxTableViewController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RxDataSources', '~> 4.0'
pod 'Then'
pod 'SnapKit', '~> 5.0.0'
  # Pods for rxTableViewController

end
